version: '3'
services:
  backend:
    image: todobackend
    container_name: todoback
    ports:
      - 3001:3001
  frontend:
    image: todofrontend
    container_name: todofront
    ports:
      - 3000:3000
    depends_on:
      - "backend"
    environment:
      - REACT_APP_API_HOST=backend
  tests:
    image: todotests
    container_name: todotests
    depends_on:
      - "frontend"
      - "backend"
    environment:
      - FRONT_HOST=frontend