version: '3'
services:
  todoback:
    image: todobackend
    container_name: todoback
    ports:
      - 3001:3001
  todofront:
    image: todofrontend
    container_name: todofront
    ports:
      - 3000:3000
    depends_on:
      - "todoback"
    environment:
      - REACT_APP_API_HOST=todoback
  todotests:
    image: todotests
    container_name: todotests
    depends_on:
      - "todofront"
      - "todoback"
    environment:
      - FRONT_HOST=todofront